### ISSUE TITLE
Celery will not start

### ISSUE THREAD

**Issue by venomgfx** [armadillica/pillar#2]
Followed the steps in the pillar-framework.org website, I'm almost there! But when running python manage.py I'm getting this:

2017-08-28 19:18:18,893     INFO pillar.PillarServer Using MongoDB database 'dillo'
2017-08-28 19:18:18,893     INFO pillar.PillarServer Configuring Celery
2017-08-28 19:18:18,894     INFO pillar.PillarServer Pinging Celery workers
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from runserver import app
  File "/mixtli/dev/pillar/dillo/runserver.py", line 10, in <module>
    app.process_extensions()
  File "/mixtli/dev/pillar/pillar/pillar/__init__.py", line 440, in process_extensions
    self.finish_startup()
  File "/mixtli/dev/pillar/pillar/pillar/__init__.py", line 571, in finish_startup
    self._config_celery()
  File "/mixtli/dev/pillar/pillar/pillar/__init__.py", line 373, in _config_celery
    self.log.info('Response: %s', self.celery.control.ping())
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/celery/app/control.py", line 235, in ping
    timeout=timeout, **kwargs)
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/kombu/pidbox.py", line 304, in _broadcast
    chan = channel or self.connection.default_channel
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/kombu/connection.py", line 819, in default_channel
    self.connection
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/amqp/connection.py", line 300, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/amqp/connection.py", line 464, in drain_events
    return self.blocking_read(timeout)
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/amqp/connection.py", line 468, in blocking_read
    frame = self.transport.read_frame()
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/amqp/transport.py", line 237, in read_frame
    frame_header = read(7, True)
  File "/home/koro/virtualenvs/dillo/lib/python3.6/site-packages/amqp/transport.py", line 377, in _read
    s = recv(n - len(rbuf))
socket.timeout: timed out

Looked at it with @fsiddi but no clue. Any idea?

**Comment by venomgfx** [comment]
Closing this for now as I cannot reproduce (it somehow fixed after trying a number of things, hard to point which one made it work).
